import { hasMinimumCompatibleRole } from "@/lib/roles";
type ChecklistPageLanguage = "it" | "en" | "fr" | "es";

const texts = {
    it: {
        common: {
            loading: "Caricamento...",
            search: "Cerca template...",
            all: "Tutti",
            error: "Errore",
            save: "Salva",
            saving: "Salvataggio...",
            cancel: "Annulla",
            back: "Indietro",
            yes: "Sì",
            no: "No",
            inactive: "Facoltativo",
            active: "Attivo",
            refresh: "Aggiorna",
        },
        templates: {
            title: "Template checklist",
            subtitle: "Gestisci i template checklist dell'organizzazione attiva.",
            new: "Nuovo template",
            total: "Template totali",
            active: "Template attivi",
            items: "Voci totali",
            listTitle: "Elenco template",
            noResults: "Nessun template trovato.",
            targetMachine: "Macchina",
            targetLine: "Linea",
            itemCount: "voci",
            version: "Versione",
            statusActive: "Attivo",
            statusInactive: "Inattivo",
            newTemplate: "Nuovo template",
            editTemplate: "Modifica template",
            editorSubtitle: "Configura nome, target e voci della checklist.",
            name: "Nome template",
            description: "Descrizione",
            target: "Target",
            targetHelp: "Scegli se la checklist è per macchina o per linea produttiva.",
            enabled: "Stato",
            itemsTitle: "Voci della checklist",
            noItems: "Nessuna voce aggiunta.",
            addItem: "Aggiungi voce",
            removeItem: "Rimuovi",
            itemTitle: "Titolo voce",
            itemDescription: "Descrizione voce",
            inputType: "Tipo input",
            required: "Obbligatorio",
            deleteConfirm: "Sei sicuro di voler rimuovere questa voce?",
            validationName: "Il nome del template è obbligatorio.",
            validationItem: "Aggiungi almeno una voce e compila il titolo per tutte.",
            saveError: "Errore durante il salvataggio.",
            loadError: "Errore durante il caricamento del template.",
            saveSuccessCreate: "Template creato con successo.",
            saveSuccessUpdate: "Nuova versione del template salvata con successo.",
        },
        inputs: {
            boolean: "Sì / No",
            text: "Testo",
            number: "Numero",
            value: "Valore",
        },
        assignments: {
            title: "Assegnazioni checklist",
            subtitle: "Assegna template checklist alle macchine dell'organizzazione attiva.",
            totalAssignments: "Assegnazioni totali",
            activeAssignments: "Assegnazioni attive",
            activeOnly: "Attive sul totale",
            newTitle: "Nuova assegnazione",
            newDescription: "Scegli template e macchina per creare una nuova assegnazione.",
            template: "Template",
            machine: "Macchina",
            selectTemplate: "Seleziona template",
            selectMachine: "Seleziona macchina",
            assign: "Assegna",
            assigning: "Assegnazione...",
            assigned: "Checklist assegnata correttamente.",
            assignError: "Errore durante il caricamento o la creazione dell'assegnazione.",
            historyTitle: "Storico assegnazioni",
            listTitle: "Storico assegnazioni",
            listDescription: "Elenco completo delle assegnazioni checklist create nel contesto attivo.",
            noResults: "Nessuna assegnazione trovata.",
            deactivate: "Disattiva",
            deactivateConfirm: "Vuoi davvero disattivare questa assegnazione?",
            deactivateError: "Errore durante la disattivazione dell'assegnazione.",
            deactivated: "Assegnazione disattivata.",
            openMachine: "Apri macchina",
            duplicate: "Questa checklist è già assegnata alla macchina selezionata.",
            missingSelection: "Seleziona un template e una macchina.",
            permissionDenied: "Permesso negato",
            onlyManagers: "Solo admin e supervisor possono modificare template e assegnazioni checklist.",
        },
        executions: {
            title: "Esecuzioni checklist",
            subtitleManufacturer: "Storico esecuzioni checklist nel contesto costruttore attivo.",
            subtitleCustomer: "Storico esecuzioni checklist nel contesto cliente attivo.",
            detailTitle: "Dettaglio esecuzione",
            loadError: "Errore caricamento esecuzioni.",
            total: "Totali",
            completed: "Completate",
            inProgress: "In corso",
            failed: "Fallite",
            searchPlaceholder: "Cerca template, macchina, work order...",
            filters: "Filtri",
            allStatuses: "Tutti gli stati",
            allPlants: "Tutti gli stabilimenti",
            results: "Risultati",
            noResults: "Nessuna esecuzione trovata.",
            detail: "Dettaglio",
            status: "Stato",
            executedAt: "Eseguita il",
            workOrder: "Work order",
            workOrderFallback: "Work order",
            machineFallback: "Macchina",
            templateFallback: "Template",
            manufacturerView: "Vista costruttore",
            customerView: "Vista cliente",
            plant: "Stabilimento",
            machine: "Macchina",
            answers: "Risposte",
            noAnswers: "Nessuna risposta registrata.",
            notes: "Note",
            value: "Valore",
            ok: "OK",
            ko: "KO",
            accessRules: "Regole di accesso",
            manufacturerRule: "Il costruttore vede tutte le esecuzioni delle macchine di sua proprietà.",
            customerRule: "Il cliente vede le esecuzioni sulle macchine a lui assegnate.",
            readonlyRule: "Le esecuzioni sono in sola lettura una volta completate.",
        },
    },
    en: {
        common: {
            loading: "Loading...",
            search: "Search template...",
            all: "All",
            error: "Error",
            save: "Save",
            saving: "Saving...",
            cancel: "Cancel",
            back: "Back",
            yes: "Yes",
            no: "No",
            inactive: "Optional",
            active: "Active",
            refresh: "Refresh",
        },
        templates: {
            title: "Checklist Templates",
            subtitle: "Manage checklist templates in the active organization.",
            new: "New template",
            total: "Total templates",
            active: "Active templates",
            items: "Total items",
            listTitle: "Template list",
            noResults: "No templates found.",
            targetMachine: "Machine",
            targetLine: "Line",
            itemCount: "items",
            version: "Version",
            statusActive: "Active",
            statusInactive: "Inactive",
            newTemplate: "New template",
            editTemplate: "Edit template",
            editorSubtitle: "Configure name, target and checklist items.",
            name: "Template name",
            description: "Description",
            target: "Target",
            targetHelp: "Choose whether the checklist is for a machine or a production line.",
            enabled: "Status",
            itemsTitle: "Checklist items",
            noItems: "No items added.",
            addItem: "Add item",
            removeItem: "Remove",
            itemTitle: "Item title",
            itemDescription: "Item description",
            inputType: "Input type",
            required: "Required",
            deleteConfirm: "Are you sure you want to remove this item?",
            validationName: "Template name is required.",
            validationItem: "Add at least one item and fill the title for all items.",
            saveError: "Error saving template.",
            loadError: "Error loading template.",
            saveSuccessCreate: "Template created successfully.",
            saveSuccessUpdate: "New template version saved successfully.",
        },
        inputs: {
            boolean: "Yes / No",
            text: "Text",
            number: "Number",
            value: "Value",
        },
        assignments: {
            title: "Checklist assignments",
            subtitle: "Assign checklist templates to machines in the active organization.",
            totalAssignments: "Total assignments",
            activeAssignments: "Active assignments",
            activeOnly: "Active share",
            newTitle: "New assignment",
            newDescription: "Choose template and machine to create a new checklist assignment.",
            template: "Template",
            machine: "Machine",
            selectTemplate: "Select template",
            selectMachine: "Select machine",
            assign: "Assign",
            assigning: "Assigning...",
            assigned: "Checklist assigned successfully.",
            assignError: "Error while loading or creating the assignment.",
            historyTitle: "Assignment history",
            listTitle: "Assignment history",
            listDescription: "Complete list of checklist assignments created in the active context.",
            noResults: "No assignments found.",
            deactivate: "Deactivate",
            deactivateConfirm: "Do you really want to deactivate this assignment?",
            deactivateError: "Error while deactivating the assignment.",
            deactivated: "Assignment deactivated.",
            openMachine: "Open machine",
            duplicate: "This checklist is already assigned to the selected machine.",
            missingSelection: "Select a template and a machine.",
            permissionDenied: "Permission denied",
            onlyManagers: "Only admins and supervisors can edit checklist templates and assignments.",
        },
        executions: {
            title: "Checklist executions",
            subtitleManufacturer: "Checklist execution history in the active manufacturer context.",
            subtitleCustomer: "Checklist execution history in the active customer context.",
            detailTitle: "Execution detail",
            loadError: "Error loading executions.",
            total: "Total",
            completed: "Completed",
            inProgress: "In progress",
            failed: "Failed",
            searchPlaceholder: "Search template, machine, work order...",
            filters: "Filters",
            allStatuses: "All statuses",
            allPlants: "All plants",
            results: "Results",
            noResults: "No executions found.",
            detail: "Detail",
            status: "Status",
            executedAt: "Executed on",
            workOrder: "Work order",
            workOrderFallback: "Work order",
            machineFallback: "Machine",
            templateFallback: "Template",
            manufacturerView: "Manufacturer view",
            customerView: "Customer view",
            plant: "Plant",
            machine: "Machine",
            answers: "Answers",
            noAnswers: "No answers recorded.",
            notes: "Notes",
            value: "Value",
            ok: "OK",
            ko: "KO",
            accessRules: "Access rules",
            manufacturerRule: "The manufacturer can see all executions on its own machines.",
            customerRule: "The customer can see executions on machines assigned to them.",
            readonlyRule: "Executions are read-only once completed.",
        },
    },
    fr: {
        common: {
            loading: "Chargement...",
            search: "Rechercher un modèle...",
            all: "Tous",
            error: "Erreur",
            save: "Enregistrer",
            saving: "Enregistrement...",
            cancel: "Annuler",
            back: "Retour",
            yes: "Oui",
            no: "Non",
            inactive: "Facultatif",
            active: "Actif",
            refresh: "Actualiser",
        },
        templates: {
            title: "Modèles de checklist",
            subtitle: "Gérez les modèles de checklist de l'organisation active.",
            new: "Nouveau modèle",
            total: "Modèles totaux",
            active: "Modèles actifs",
            items: "Éléments totaux",
            listTitle: "Liste des modèles",
            noResults: "Aucun modèle trouvé.",
            targetMachine: "Machine",
            targetLine: "Ligne",
            itemCount: "éléments",
            version: "Version",
            statusActive: "Actif",
            statusInactive: "Inactif",
            newTemplate: "Nouveau modèle",
            editTemplate: "Modifier le modèle",
            editorSubtitle: "Configurez le nom, la cible et les éléments de la checklist.",
            name: "Nom du modèle",
            description: "Description",
            target: "Cible",
            targetHelp: "Choisissez si la checklist concerne une machine ou une ligne de production.",
            enabled: "Statut",
            itemsTitle: "Éléments de la checklist",
            noItems: "Aucun élément ajouté.",
            addItem: "Ajouter un élément",
            removeItem: "Supprimer",
            itemTitle: "Titre de l'élément",
            itemDescription: "Description de l'élément",
            inputType: "Type de saisie",
            required: "Obligatoire",
            deleteConfirm: "Voulez-vous vraiment supprimer cet élément ?",
            validationName: "Le nom du modèle est obligatoire.",
            validationItem: "Ajoutez au moins un élément et renseignez un titre pour chacun.",
            saveError: "Erreur lors de l'enregistrement du modèle.",
            loadError: "Erreur lors du chargement du modèle.",
            saveSuccessCreate: "Modèle créé avec succès.",
            saveSuccessUpdate: "Nouvelle version du modèle enregistrée avec succès.",
        },
        inputs: {
            boolean: "Oui / Non",
            text: "Texte",
            number: "Nombre",
            value: "Valeur",
        },
        assignments: {
            title: "Affectations checklist",
            subtitle: "Affectez des modèles de checklist aux machines de l'organisation active.",
            totalAssignments: "Affectations totales",
            activeAssignments: "Affectations actives",
            activeOnly: "Part active",
            newTitle: "Nouvelle affectation",
            newDescription: "Choisissez un modèle et une machine pour créer une nouvelle affectation.",
            template: "Modèle",
            machine: "Machine",
            selectTemplate: "Sélectionner un modèle",
            selectMachine: "Sélectionner une machine",
            assign: "Affecter",
            assigning: "Affectation...",
            assigned: "Checklist affectée avec succès.",
            assignError: "Erreur lors du chargement ou de la création de l'affectation.",
            historyTitle: "Historique des affectations",
            listTitle: "Historique des affectations",
            listDescription: "Liste complète des affectations de checklist créées dans le contexte actif.",
            noResults: "Aucune affectation trouvée.",
            deactivate: "Désactiver",
            deactivateConfirm: "Voulez-vous vraiment désactiver cette affectation ?",
            deactivateError: "Erreur lors de la désactivation de l'affectation.",
            deactivated: "Affectation désactivée.",
            openMachine: "Ouvrir la machine",
            duplicate: "Cette checklist est déjà affectée à la machine sélectionnée.",
            missingSelection: "Sélectionnez un modèle et une machine.",
            permissionDenied: "Permission refusée",
            onlyManagers: "Seuls les administrateurs et superviseurs peuvent modifier les modèles et affectations de checklist.",
        },
        executions: {
            title: "Exécutions de checklist",
            subtitleManufacturer: "Historique des exécutions dans le contexte fabricant actif.",
            subtitleCustomer: "Historique des exécutions dans le contexte client actif.",
            detailTitle: "Détail de l'exécution",
            loadError: "Erreur lors du chargement des exécutions.",
            total: "Total",
            completed: "Terminées",
            inProgress: "En cours",
            failed: "Échouées",
            searchPlaceholder: "Rechercher un modèle, une machine, un ordre de travail...",
            filters: "Filtres",
            allStatuses: "Tous les statuts",
            allPlants: "Tous les sites",
            results: "Résultats",
            noResults: "Aucune exécution trouvée.",
            detail: "Détail",
            status: "Statut",
            executedAt: "Exécutée le",
            workOrder: "Ordre de travail",
            workOrderFallback: "Ordre de travail",
            machineFallback: "Machine",
            templateFallback: "Modèle",
            manufacturerView: "Vue fabricant",
            customerView: "Vue client",
            plant: "Site",
            machine: "Machine",
            answers: "Réponses",
            noAnswers: "Aucune réponse enregistrée.",
            notes: "Notes",
            value: "Valeur",
            ok: "OK",
            ko: "KO",
            accessRules: "Règles d'accès",
            manufacturerRule: "Le fabricant voit toutes les exécutions de ses propres machines.",
            customerRule: "Le client voit les exécutions des machines qui lui sont affectées.",
            readonlyRule: "Les exécutions sont en lecture seule une fois terminées.",
        },
    },
    es: {
        common: {
            loading: "Cargando...",
            search: "Buscar plantilla...",
            all: "Todos",
            error: "Error",
            save: "Guardar",
            saving: "Guardando...",
            cancel: "Cancelar",
            back: "Volver",
            yes: "Sí",
            no: "No",
            inactive: "Opcional",
            active: "Activo",
            refresh: "Actualizar",
        },
        templates: {
            title: "Plantillas de checklist",
            subtitle: "Gestiona las plantillas de checklist de la organización activa.",
            new: "Nueva plantilla",
            total: "Plantillas totales",
            active: "Plantillas activas",
            items: "Elementos totales",
            listTitle: "Lista de plantillas",
            noResults: "No se encontraron plantillas.",
            targetMachine: "Máquina",
            targetLine: "Línea",
            itemCount: "elementos",
            version: "Versión",
            statusActive: "Activa",
            statusInactive: "Inactiva",
            newTemplate: "Nueva plantilla",
            editTemplate: "Editar plantilla",
            editorSubtitle: "Configura nombre, objetivo y elementos de la checklist.",
            name: "Nombre de la plantilla",
            description: "Descripción",
            target: "Objetivo",
            targetHelp: "Elige si la checklist es para una máquina o una línea de producción.",
            enabled: "Estado",
            itemsTitle: "Elementos de la checklist",
            noItems: "No se han añadido elementos.",
            addItem: "Añadir elemento",
            removeItem: "Eliminar",
            itemTitle: "Título del elemento",
            itemDescription: "Descripción del elemento",
            inputType: "Tipo de entrada",
            required: "Obligatorio",
            deleteConfirm: "¿Seguro que quieres eliminar este elemento?",
            validationName: "El nombre de la plantilla es obligatorio.",
            validationItem: "Añade al menos un elemento y completa el título de todos.",
            saveError: "Error al guardar.",
            loadError: "Error al cargar la plantilla.",
            saveSuccessCreate: "Plantilla creada correctamente.",
            saveSuccessUpdate: "Nueva versión de la plantilla guardada correctamente.",
        },
        inputs: {
            boolean: "Sí / No",
            text: "Texto",
            number: "Número",
            value: "Valor",
        },
        assignments: {
            title: "Asignaciones de checklist",
            subtitle: "Asigna plantillas de checklist a las máquinas de la organización activa.",
            totalAssignments: "Asignaciones totales",
            activeAssignments: "Asignaciones activas",
            activeOnly: "Parte activa",
            newTitle: "Nueva asignación",
            newDescription: "Elige plantilla y máquina para crear una nueva asignación.",
            template: "Plantilla",
            machine: "Máquina",
            selectTemplate: "Selecciona plantilla",
            selectMachine: "Selecciona máquina",
            assign: "Asignar",
            assigning: "Asignando...",
            assigned: "Checklist asignada correctamente.",
            assignError: "Error al cargar o crear la asignación.",
            historyTitle: "Historial de asignaciones",
            listTitle: "Historial de asignaciones",
            listDescription: "Lista completa de asignaciones de checklist creadas en el contexto activo.",
            noResults: "No se encontraron asignaciones.",
            deactivate: "Desactivar",
            deactivateConfirm: "¿Seguro que quieres desactivar esta asignación?",
            deactivateError: "Error al desactivar la asignación.",
            deactivated: "Asignación desactivada.",
            openMachine: "Abrir máquina",
            duplicate: "Esta checklist ya está asignada a la máquina seleccionada.",
            missingSelection: "Selecciona una plantilla y una máquina.",
            permissionDenied: "Permiso denegado",
            onlyManagers: "Solo administradores y supervisores pueden editar plantillas y asignaciones de checklist.",
        },
        executions: {
            title: "Ejecuciones de checklist",
            subtitleManufacturer: "Historial de ejecuciones en el contexto fabricante activo.",
            subtitleCustomer: "Historial de ejecuciones en el contexto cliente activo.",
            detailTitle: "Detalle de ejecución",
            loadError: "Error al cargar ejecuciones.",
            total: "Total",
            completed: "Completadas",
            inProgress: "En curso",
            failed: "Fallidas",
            searchPlaceholder: "Buscar plantilla, máquina, orden de trabajo...",
            filters: "Filtros",
            allStatuses: "Todos los estados",
            allPlants: "Todas las plantas",
            results: "Resultados",
            noResults: "No se encontraron ejecuciones.",
            detail: "Detalle",
            status: "Estado",
            executedAt: "Ejecutada el",
            workOrder: "Orden de trabajo",
            workOrderFallback: "Orden de trabajo",
            machineFallback: "Máquina",
            templateFallback: "Plantilla",
            manufacturerView: "Vista fabricante",
            customerView: "Vista cliente",
            plant: "Planta",
            machine: "Máquina",
            answers: "Respuestas",
            noAnswers: "No se registraron respuestas.",
            notes: "Notas",
            value: "Valor",
            ok: "OK",
            ko: "KO",
            accessRules: "Reglas de acceso",
            manufacturerRule: "El fabricante puede ver todas las ejecuciones de sus máquinas.",
            customerRule: "El cliente puede ver las ejecuciones de las máquinas asignadas.",
            readonlyRule: "Las ejecuciones son de solo lectura una vez completadas.",
        },
    },
} as const;

export function getChecklistTexts(language?: string) {
    const lang = (language || "it") as ChecklistPageLanguage;
    return texts[lang] ?? texts.it;
}

export function translateChecklistTarget(targetType: string | null | undefined, language?: string) {
    const t = getChecklistTexts(language);
    if (targetType === "production_line") return t.templates.targetLine;
    return t.templates.targetMachine;
}

export function formatChecklistDate(value: string | null | undefined, language?: string) {
    if (!value) return "—";
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return value;
    const locale =
        language === "it" ? "it-IT" : language === "fr" ? "fr-FR" : language === "es" ? "es-ES" : "en-GB";
    return date.toLocaleDateString(locale, { year: "numeric", month: "2-digit", day: "2-digit" });
}

export function canManageChecklists(role: string | null | undefined): boolean {
    return hasMinimumCompatibleRole(role, "supervisor");
}

const inputTypeLabels: Record<string, Record<string, string>> = {
    it: { boolean: "Sì / No", text: "Testo", number: "Numero", value: "Valore", checkbox: "Checkbox", select: "Selezione", photo: "Foto", signature: "Firma", date: "Data", textarea: "Testo lungo" },
    en: { boolean: "Yes / No", text: "Text", number: "Number", value: "Value", checkbox: "Checkbox", select: "Selection", photo: "Photo", signature: "Signature", date: "Date", textarea: "Long text" },
    fr: { boolean: "Oui / Non", text: "Texte", number: "Nombre", value: "Valeur", checkbox: "Case à cocher", select: "Sélection", photo: "Photo", signature: "Signature", date: "Date", textarea: "Texte long" },
    es: { boolean: "Sí / No", text: "Texto", number: "Número", value: "Valor", checkbox: "Casilla", select: "Selección", photo: "Foto", signature: "Firma", date: "Fecha", textarea: "Texto largo" },
};

export function translateChecklistInputType(inputType: string | null | undefined, language?: string): string {
    const lang = (language || "it") as ChecklistPageLanguage;
    const labels = inputTypeLabels[lang] ?? inputTypeLabels.it;
    return labels[inputType ?? ""] ?? (inputType || "—");
}

export function normalizeExecutionStatus(status: string | null | undefined): "completed" | "in_progress" | "failed" | "unknown" {
    const s = (status ?? "").toLowerCase().trim();
    if (["completed", "pass", "passed", "done", "ok"].includes(s)) return "completed";
    if (["in_progress", "pending", "started", "partial", "in-progress"].includes(s)) return "in_progress";
    if (["failed", "fail", "error", "rejected", "not_passed"].includes(s)) return "failed";
    return "unknown";
}
