import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "it" | "en" | "fr" | "es";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    it: {
        // Common
        "common.loading": "Caricamento...",
        "common.save": "Salva",
        "common.cancel": "Annulla",
        "common.delete": "Elimina",
        "common.edit": "Modifica",
        "common.create": "Crea",
        "common.search": "Cerca",
        "common.filter": "Filtra",
        "common.export": "Esporta",
        "common.back": "Indietro",
        "common.next": "Avanti",
        "common.confirm": "Conferma",
        "common.close": "Chiudi",
        "common.yes": "Sì",
        "common.no": "No",
        "common.all": "Tutti",
        "common.none": "Nessuno",
        "common.actions": "Azioni",
        "common.status": "Stato",
        "common.date": "Data",
        "common.time": "Ora",
        "common.name": "Nome",
        "common.description": "Descrizione",
        "common.notes": "Note",
        "common.priority": "Priorità",
        "common.high": "Alta",
        "common.medium": "Media",
        "common.low": "Bassa",
        "common.success": "Successo",
        "common.error": "Errore",
        "common.warning": "Attenzione",

        // Navigation
        "nav.dashboard": "Dashboard",
        "nav.equipment": "Attrezzature",
        "nav.maintenance": "Manutenzione",
        "nav.checklists": "Checklist",
        "nav.analytics": "Analisi",
        "nav.settings": "Impostazioni",
        "nav.users": "Utenti",
        "nav.notifications": "Notifiche",
        "nav.logout": "Esci",
        "nav.scanner": "Scanner QR",

        // Dashboard
        "dashboard.title": "Dashboard",
        "dashboard.welcome": "Bentornato",
        "dashboard.totalEquipment": "Attrezzature Totali",
        "dashboard.pendingMaintenance": "Manutenzioni in Attesa",
        "dashboard.completedToday": "Completate Oggi",
        "dashboard.activeChecklists": "Checklist Attive",
        "dashboard.upcomingMaintenance": "Prossime Manutenzioni",
        "dashboard.recentActivity": "Attività Recenti",
        "dashboard.quickActions": "Azioni Rapide",
        "dashboard.newMaintenance": "Nuova Manutenzione",
        "dashboard.newChecklist": "Nuova Checklist",
        "dashboard.scanQR": "Scansiona QR",
        "dashboard.viewAll": "Vedi Tutto",
        "dashboard.noUpcoming": "Nessuna manutenzione programmata",
        "dashboard.noActivity": "Nessuna attività recente",
        "dashboard.language": "Lingua",
        "dashboard.selectLanguage": "Seleziona Lingua",

        // Equipment
        "equipment.title": "Attrezzature",
        "equipment.subtitle": "Gestisci e monitora tutte le attrezzature",
        "equipment.new": "Nuova Attrezzatura",
        "equipment.edit": "Modifica Attrezzatura",
        "equipment.details": "Dettagli Attrezzatura",
        "equipment.name": "Nome Attrezzatura",
        "equipment.code": "Codice Attrezzatura",
        "equipment.type": "Tipo",
        "equipment.category": "Categoria",
        "equipment.location": "Posizione",
        "equipment.serialNumber": "Numero Seriale",
        "equipment.manufacturer": "Produttore",
        "equipment.model": "Modello",
        "equipment.purchaseDate": "Data Acquisto",
        "equipment.warrantyExpiry": "Scadenza Garanzia",
        "equipment.status": "Stato",
        "equipment.active": "Attivo",
        "equipment.inactive": "Inattivo",
        "equipment.maintenance": "In Manutenzione",
        "equipment.decommissioned": "Dismesso",
        "equipment.documents": "Documenti",
        "equipment.qrCode": "Codice QR",
        "equipment.noEquipment": "Nessuna attrezzatura trovata",
        "equipment.noEquipmentDesc": "Inizia aggiungendo la tua prima attrezzatura",
        "equipment.deleteConfirm": "Sei sicuro di voler eliminare questa attrezzatura?",
        "equipment.addEquipment": "Aggiungi Attrezzatura",
        "equipment.addFirst": "Aggiungi Prima Attrezzatura",
        "equipment.generic": "Generico",
        "equipment.technicalSpecs": "Specifiche Tecniche",
        "equipment.technicalSpecsPlaceholder": "Inserisci le specifiche tecniche...",
        "equipment.notesPlaceholder": "Note aggiuntive...",
        "equipment.saving": "Salvataggio...",
        "equipment.saveEquipment": "Salva Attrezzatura",
        "equipment.showQR": "Mostra Generatore QR",
        "equipment.hideQR": "Nascondi Generatore QR",
        "equipment.qrGenerator": "Generatore Codice QR",
        "equipment.information": "Informazioni Attrezzatura",
        "equipment.required": "obbligatorio",
        "equipment.namePlaceholder": "Inserisci nome attrezzatura",
        "equipment.codePlaceholder": "Inserisci codice attrezzatura",
        "equipment.typePlaceholder": "es. Compressore, Pompa",
        "equipment.categoryPlaceholder": "es. Macchinario, Utensile",
        "equipment.locationPlaceholder": "es. Magazzino A, Piano 2",
        "equipment.serialNumberPlaceholder": "Inserisci numero seriale",
        "equipment.manufacturerPlaceholder": "Inserisci produttore",
        "equipment.modelPlaceholder": "Inserisci modello",

        // Maintenance
        "maintenance.title": "Manutenzione",
        "maintenance.subtitle": "Gestisci e monitora tutte le manutenzioni",
        "maintenance.addMaintenance": "Nuova Manutenzione",
        "maintenance.addFirst": "Aggiungi Prima Manutenzione",
        "maintenance.noMaintenance": "Nessuna manutenzione trovata",
        "maintenance.noMaintenanceDesc": "Inizia aggiungendo la tua prima manutenzione",
        "maintenance.new": "Nuova Manutenzione",
        "maintenance.newMaintenance": "Nuova Manutenzione",
        "maintenance.edit": "Modifica Manutenzione",
        "maintenance.details": "Dettagli Manutenzione",
        "maintenance.scheduled": "Programmata",
        "maintenance.inProgress": "In Corso",
        "maintenance.completed": "Completata",
        "maintenance.cancelled": "Annullata",
        "maintenance.pending": "In Attesa",
        "maintenance.type": "Tipo Manutenzione",
        "maintenance.preventive": "Preventiva",
        "maintenance.corrective": "Correttiva",
        "maintenance.predictive": "Predittiva",
        "maintenance.scheduledDate": "Data Programmata",
        "maintenance.completedDate": "Data Completamento",
        "maintenance.technician": "Tecnico",
        "maintenance.cost": "Costo",
        "maintenance.deleteConfirm": "Sei sicuro di voler eliminare questa manutenzione?",
        "maintenance.selectEquipment": "Seleziona Attrezzatura",
        "maintenance.selectTechnician": "Seleziona Tecnico",
        "maintenance.frequency": "Frequenza",
        "maintenance.daily": "Giornaliera",
        "maintenance.weekly": "Settimanale",
        "maintenance.monthly": "Mensile",
        "maintenance.quarterly": "Trimestrale",
        "maintenance.yearly": "Annuale",
        "maintenance.nextDue": "Prossima Scadenza",
        "maintenance.assignTo": "Assegna a",
        "maintenance.titleLabel": "Titolo",
        "maintenance.titlePlaceholder": "Inserisci titolo manutenzione",
        "maintenance.descriptionPlaceholder": "Descrizione della manutenzione...",
        "maintenance.createSuccess": "Manutenzione creata con successo",
        "maintenance.createError": "Errore durante la creazione",
        "maintenance.updateSuccess": "Manutenzione aggiornata con successo",
        "maintenance.updateError": "Errore durante l'aggiornamento",

        // Checklists
        "checklists.title": "Checklist",
        "checklists.subtitle": "Gestisci e monitora tutte le checklist",
        "checklists.addChecklist": "Nuova Checklist",
        "checklists.addFirst": "Aggiungi Prima Checklist",
        "checklists.noChecklists": "Nessuna checklist trovata",
        "checklists.noChecklistsDesc": "Inizia aggiungendo la tua prima checklist",
        "checklists.newChecklist": "Nuova Checklist",
        "checklists.newChecklistDesc": "Crea un nuovo modello di checklist con gli elementi da verificare",
        "checklists.active": "Attiva",
        "checklists.inactive": "Inattiva",
        "checklists.items": "elementi",
        "checklists.execute": "Esegui",
        "checklists.confirmDelete": "Sei sicuro di voler eliminare questa checklist?",
        "checklists.deleteSuccess": "Checklist eliminata con successo",
        "checklists.deleteError": "Errore durante l'eliminazione",
        "checklists.createSuccess": "Checklist creata con successo",
        "checklists.createError": "Errore durante la creazione",
        "checklists.checklistTitle": "Titolo Checklist",
        "checklists.titlePlaceholder": "Inserisci titolo checklist",
        "checklists.titleRequired": "Il titolo è obbligatorio",
        "checklists.category": "Categoria",
        "checklists.categoryPlaceholder": "es. Manutenzione Preventiva",
        "checklists.categoryRequired": "La categoria è obbligatoria",
        "checklists.equipmentType": "Tipo Attrezzatura",
        "checklists.equipmentTypePlaceholder": "es. Compressore, Pompa",
        "checklists.descriptionPlaceholder": "Descrizione della checklist...",
        "checklists.checklistItems": "Elementi Checklist",
        "checklists.addItem": "Aggiungi Elemento",
        "checklists.itemTitle": "Titolo Elemento",
        "checklists.itemTitlePlaceholder": "es. Verificare livello olio",
        "checklists.itemDescription": "Descrizione",
        "checklists.itemDescPlaceholder": "Istruzioni aggiuntive...",
        "checklists.requiredField": "Campo obbligatorio",
        "checklists.itemRequired": "Aggiungi almeno un elemento",
        "checklists.associatedChecklist": "Checklist Associata",
        "checklists.selectChecklist": "Seleziona Checklist",
        "checklists.completeAll": "Completa tutti gli elementi prima di finalizzare",
        "checklists.confirmComplete": "Conferma il completamento della checklist",
        "checklists.clearSignature": "Cancella Firma",
        "checklists.saveSignature": "Salva la firma per utilizzi futuri",
        "checklists.confirmAndSend": "Conferma e Invia",

        // Users
        "users.title": "Gestione Utenti",
        "users.new": "Nuovo Utente",
        "users.edit": "Modifica Utente",
        "users.email": "Email",
        "users.password": "Password",
        "users.role": "Ruolo",
        "users.admin": "Amministratore",
        "users.technician": "Tecnico",
        "users.viewer": "Visualizzatore",
        "users.lastLogin": "Ultimo Accesso",
        "users.noUsers": "Nessun utente trovato",
        "users.deleteConfirm": "Sei sicuro di voler eliminare questo utente?",

        // Settings
        "settings.title": "Impostazioni",
        "settings.profile": "Profilo",
        "settings.security": "Sicurezza",
        "settings.notifications": "Notifiche",
        "settings.appearance": "Aspetto",
        "settings.language": "Lingua",
        "settings.theme": "Tema",
        "settings.darkMode": "Modalità Scura",
        "settings.lightMode": "Modalità Chiara",
        "settings.changePassword": "Cambia Password",
        "settings.twoFactor": "Autenticazione a Due Fattori",
        "settings.emailNotifications": "Notifiche Email",
        "settings.pushNotifications": "Notifiche Push",

        // Auth
        "auth.login": "Accedi",
        "auth.logout": "Esci",
        "auth.register": "Registrati",
        "auth.forgotPassword": "Password Dimenticata?",
        "auth.resetPassword": "Reimposta Password",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.confirmPassword": "Conferma Password",
        "auth.rememberMe": "Ricordami",
        "auth.noAccount": "Non hai un account?",
        "auth.hasAccount": "Hai già un account?",
        "auth.invalidCredentials": "Credenziali non valide",
        "auth.loginSuccess": "Accesso effettuato con successo",
        "auth.logoutSuccess": "Disconnessione effettuata",

        // Scanner
        "scanner.title": "Scanner QR",
        "scanner.scan": "Scansiona",
        "scanner.scanning": "Scansione in corso...",
        "scanner.noCamera": "Nessuna fotocamera trovata",
        "scanner.permissionDenied": "Permesso fotocamera negato",
        "scanner.equipmentFound": "Attrezzatura trovata",
        "scanner.equipmentNotFound": "Attrezzatura non trovata",

        // Notifications
        "notifications.title": "Notifiche",
        "notifications.markAllRead": "Segna tutte come lette",
        "notifications.noNotifications": "Nessuna notifica",
        "notifications.new": "Nuova",

        // Analytics
        "analytics.title": "Analisi",
        "analytics.checklistExecutions": "Esecuzioni Checklist",
        "analytics.maintenanceStats": "Statistiche Manutenzione",
        "analytics.equipmentStatus": "Stato Attrezzature",
        "analytics.period": "Periodo",
        "analytics.today": "Oggi",
        "analytics.thisWeek": "Questa Settimana",
        "analytics.thisMonth": "Questo Mese",
        "analytics.thisYear": "Quest'Anno",
    },

    en: {
        // Common
        "common.loading": "Loading...",
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.create": "Create",
        "common.search": "Search",
        "common.filter": "Filter",
        "common.export": "Export",
        "common.back": "Back",
        "common.next": "Next",
        "common.confirm": "Confirm",
        "common.close": "Close",
        "common.yes": "Yes",
        "common.no": "No",
        "common.all": "All",
        "common.none": "None",
        "common.actions": "Actions",
        "common.status": "Status",
        "common.date": "Date",
        "common.time": "Time",
        "common.name": "Name",
        "common.description": "Description",
        "common.notes": "Notes",
        "common.priority": "Priority",
        "common.high": "High",
        "common.medium": "Medium",
        "common.low": "Low",
        "common.success": "Success",
        "common.error": "Error",
        "common.warning": "Warning",

        // Navigation
        "nav.dashboard": "Dashboard",
        "nav.equipment": "Equipment",
        "nav.maintenance": "Maintenance",
        "nav.checklists": "Checklists",
        "nav.analytics": "Analytics",
        "nav.settings": "Settings",
        "nav.users": "Users",
        "nav.notifications": "Notifications",
        "nav.logout": "Logout",
        "nav.scanner": "QR Scanner",

        // Dashboard
        "dashboard.title": "Dashboard",
        "dashboard.welcome": "Welcome back",
        "dashboard.totalEquipment": "Total Equipment",
        "dashboard.pendingMaintenance": "Pending Maintenance",
        "dashboard.completedToday": "Completed Today",
        "dashboard.activeChecklists": "Active Checklists",
        "dashboard.upcomingMaintenance": "Upcoming Maintenance",
        "dashboard.recentActivity": "Recent Activity",
        "dashboard.quickActions": "Quick Actions",
        "dashboard.newMaintenance": "New Maintenance",
        "dashboard.newChecklist": "New Checklist",
        "dashboard.scanQR": "Scan QR",
        "dashboard.viewAll": "View All",
        "dashboard.noUpcoming": "No scheduled maintenance",
        "dashboard.noActivity": "No recent activity",
        "dashboard.language": "Language",
        "dashboard.selectLanguage": "Select Language",

        // Equipment
        "equipment.title": "Equipment",
        "equipment.subtitle": "Manage and monitor all equipment",
        "equipment.new": "New Equipment",
        "equipment.edit": "Edit Equipment",
        "equipment.details": "Equipment Details",
        "equipment.name": "Equipment Name",
        "equipment.code": "Equipment Code",
        "equipment.type": "Type",
        "equipment.category": "Category",
        "equipment.location": "Location",
        "equipment.serialNumber": "Serial Number",
        "equipment.manufacturer": "Manufacturer",
        "equipment.model": "Model",
        "equipment.purchaseDate": "Purchase Date",
        "equipment.warrantyExpiry": "Warranty Expiry",
        "equipment.status": "Status",
        "equipment.active": "Active",
        "equipment.inactive": "Inactive",
        "equipment.maintenance": "Under Maintenance",
        "equipment.decommissioned": "Decommissioned",
        "equipment.documents": "Documents",
        "equipment.qrCode": "QR Code",
        "equipment.noEquipment": "No equipment found",
        "equipment.noEquipmentDesc": "Start by adding your first equipment",
        "equipment.deleteConfirm": "Are you sure you want to delete this equipment?",
        "equipment.addEquipment": "Add Equipment",
        "equipment.addFirst": "Add First Equipment",
        "equipment.generic": "Generic",
        "equipment.technicalSpecs": "Technical Specifications",
        "equipment.technicalSpecsPlaceholder": "Enter technical specifications...",
        "equipment.notesPlaceholder": "Additional notes...",
        "equipment.saving": "Saving...",
        "equipment.saveEquipment": "Save Equipment",
        "equipment.showQR": "Show QR Generator",
        "equipment.hideQR": "Hide QR Generator",
        "equipment.qrGenerator": "QR Code Generator",
        "equipment.information": "Equipment Information",
        "equipment.required": "required",
        "equipment.namePlaceholder": "Enter equipment name",
        "equipment.codePlaceholder": "Enter equipment code",
        "equipment.typePlaceholder": "e.g. Compressor, Pump",
        "equipment.categoryPlaceholder": "e.g. Machinery, Tool",
        "equipment.locationPlaceholder": "e.g. Warehouse A, Floor 2",
        "equipment.serialNumberPlaceholder": "Enter serial number",
        "equipment.manufacturerPlaceholder": "Enter manufacturer",
        "equipment.modelPlaceholder": "Enter model",

        // Maintenance
        "maintenance.title": "Maintenance",
        "maintenance.subtitle": "Manage and monitor all maintenance tasks",
        "maintenance.addMaintenance": "New Maintenance",
        "maintenance.addFirst": "Add First Maintenance",
        "maintenance.noMaintenance": "No maintenance found",
        "maintenance.noMaintenanceDesc": "Start by adding your first maintenance task",
        "maintenance.new": "New Maintenance",
        "maintenance.newMaintenance": "New Maintenance",
        "maintenance.edit": "Edit Maintenance",
        "maintenance.details": "Maintenance Details",
        "maintenance.scheduled": "Scheduled",
        "maintenance.inProgress": "In Progress",
        "maintenance.completed": "Completed",
        "maintenance.cancelled": "Cancelled",
        "maintenance.pending": "Pending",
        "maintenance.type": "Maintenance Type",
        "maintenance.preventive": "Preventive",
        "maintenance.corrective": "Corrective",
        "maintenance.predictive": "Predictive",
        "maintenance.scheduledDate": "Scheduled Date",
        "maintenance.completedDate": "Completion Date",
        "maintenance.technician": "Technician",
        "maintenance.cost": "Cost",
        "maintenance.deleteConfirm": "Are you sure you want to delete this maintenance?",
        "maintenance.selectEquipment": "Select Equipment",
        "maintenance.selectTechnician": "Select Technician",
        "maintenance.frequency": "Frequency",
        "maintenance.daily": "Daily",
        "maintenance.weekly": "Weekly",
        "maintenance.monthly": "Monthly",
        "maintenance.quarterly": "Quarterly",
        "maintenance.yearly": "Yearly",
        "maintenance.nextDue": "Next Due Date",
        "maintenance.assignTo": "Assign To",
        "maintenance.titleLabel": "Title",
        "maintenance.titlePlaceholder": "Enter maintenance title",
        "maintenance.descriptionPlaceholder": "Maintenance description...",
        "maintenance.createSuccess": "Maintenance created successfully",
        "maintenance.createError": "Error creating maintenance",
        "maintenance.updateSuccess": "Maintenance updated successfully",
        "maintenance.updateError": "Error updating maintenance",

        // Checklists
        "checklists.title": "Checklists",
        "checklists.subtitle": "Manage and monitor all checklists",
        "checklists.addChecklist": "New Checklist",
        "checklists.addFirst": "Add First Checklist",
        "checklists.noChecklists": "No checklists found",
        "checklists.noChecklistsDesc": "Start by adding your first checklist",
        "checklists.newChecklist": "New Checklist",
        "checklists.newChecklistDesc": "Create a new checklist template with items to verify",
        "checklists.active": "Active",
        "checklists.inactive": "Inactive",
        "checklists.items": "items",
        "checklists.execute": "Execute",
        "checklists.confirmDelete": "Are you sure you want to delete this checklist?",
        "checklists.deleteSuccess": "Checklist deleted successfully",
        "checklists.deleteError": "Error deleting checklist",
        "checklists.createSuccess": "Checklist created successfully",
        "checklists.createError": "Error creating checklist",
        "checklists.checklistTitle": "Checklist Title",
        "checklists.titlePlaceholder": "Enter checklist title",
        "checklists.titleRequired": "Title is required",
        "checklists.category": "Category",
        "checklists.categoryPlaceholder": "e.g. Preventive Maintenance",
        "checklists.categoryRequired": "Category is required",
        "checklists.equipmentType": "Equipment Type",
        "checklists.equipmentTypePlaceholder": "e.g. Compressor, Pump",
        "checklists.descriptionPlaceholder": "Checklist description...",
        "checklists.checklistItems": "Checklist Items",
        "checklists.addItem": "Add Item",
        "checklists.itemTitle": "Item Title",
        "checklists.itemTitlePlaceholder": "e.g. Check oil level",
        "checklists.itemDescription": "Description",
        "checklists.itemDescPlaceholder": "Additional instructions...",
        "checklists.requiredField": "Required field",
        "checklists.itemRequired": "Add at least one item",
        "checklists.associatedChecklist": "Associated Checklist",
        "checklists.selectChecklist": "Select Checklist",
        "checklists.completeAll": "Complete all items before finalizing",
        "checklists.confirmComplete": "Confirm checklist completion",
        "checklists.clearSignature": "Clear Signature",
        "checklists.saveSignature": "Save signature for future use",
        "checklists.confirmAndSend": "Confirm and Send",

        // Users
        "users.title": "User Management",
        "users.new": "New User",
        "users.edit": "Edit User",
        "users.email": "Email",
        "users.password": "Password",
        "users.role": "Role",
        "users.admin": "Administrator",
        "users.technician": "Technician",
        "users.viewer": "Viewer",
        "users.lastLogin": "Last Login",
        "users.noUsers": "No users found",
        "users.deleteConfirm": "Are you sure you want to delete this user?",

        // Settings
        "settings.title": "Settings",
        "settings.profile": "Profile",
        "settings.security": "Security",
        "settings.notifications": "Notifications",
        "settings.appearance": "Appearance",
        "settings.language": "Language",
        "settings.theme": "Theme",
        "settings.darkMode": "Dark Mode",
        "settings.lightMode": "Light Mode",
        "settings.changePassword": "Change Password",
        "settings.twoFactor": "Two-Factor Authentication",
        "settings.emailNotifications": "Email Notifications",
        "settings.pushNotifications": "Push Notifications",

        // Auth
        "auth.login": "Login",
        "auth.logout": "Logout",
        "auth.register": "Register",
        "auth.forgotPassword": "Forgot Password?",
        "auth.resetPassword": "Reset Password",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.confirmPassword": "Confirm Password",
        "auth.rememberMe": "Remember Me",
        "auth.noAccount": "Don't have an account?",
        "auth.hasAccount": "Already have an account?",
        "auth.invalidCredentials": "Invalid credentials",
        "auth.loginSuccess": "Login successful",
        "auth.logoutSuccess": "Logout successful",

        // Scanner
        "scanner.title": "QR Scanner",
        "scanner.scan": "Scan",
        "scanner.scanning": "Scanning...",
        "scanner.noCamera": "No camera found",
        "scanner.permissionDenied": "Camera permission denied",
        "scanner.equipmentFound": "Equipment found",
        "scanner.equipmentNotFound": "Equipment not found",

        // Notifications
        "notifications.title": "Notifications",
        "notifications.markAllRead": "Mark all as read",
        "notifications.noNotifications": "No notifications",
        "notifications.new": "New",

        // Analytics
        "analytics.title": "Analytics",
        "analytics.checklistExecutions": "Checklist Executions",
        "analytics.maintenanceStats": "Maintenance Statistics",
        "analytics.equipmentStatus": "Equipment Status",
        "analytics.period": "Period",
        "analytics.today": "Today",
        "analytics.thisWeek": "This Week",
        "analytics.thisMonth": "This Month",
        "analytics.thisYear": "This Year",
    },

    fr: {
        // Common
        "common.loading": "Chargement...",
        "common.save": "Enregistrer",
        "common.cancel": "Annuler",
        "common.delete": "Supprimer",
        "common.edit": "Modifier",
        "common.create": "Créer",
        "common.search": "Rechercher",
        "common.filter": "Filtrer",
        "common.export": "Exporter",
        "common.back": "Retour",
        "common.next": "Suivant",
        "common.confirm": "Confirmer",
        "common.close": "Fermer",
        "common.yes": "Oui",
        "common.no": "Non",
        "common.all": "Tous",
        "common.none": "Aucun",
        "common.actions": "Actions",
        "common.status": "Statut",
        "common.date": "Date",
        "common.time": "Heure",
        "common.name": "Nom",
        "common.description": "Description",
        "common.notes": "Notes",
        "common.priority": "Priorité",
        "common.high": "Haute",
        "common.medium": "Moyenne",
        "common.low": "Basse",
        "common.success": "Succès",
        "common.error": "Erreur",
        "common.warning": "Attention",

        // Navigation
        "nav.dashboard": "Tableau de bord",
        "nav.equipment": "Équipements",
        "nav.maintenance": "Maintenance",
        "nav.checklists": "Checklists",
        "nav.analytics": "Analyses",
        "nav.settings": "Paramètres",
        "nav.users": "Utilisateurs",
        "nav.notifications": "Notifications",
        "nav.logout": "Déconnexion",
        "nav.scanner": "Scanner QR",

        // Dashboard
        "dashboard.title": "Tableau de bord",
        "dashboard.welcome": "Bienvenue",
        "dashboard.totalEquipment": "Équipements Totaux",
        "dashboard.pendingMaintenance": "Maintenances en Attente",
        "dashboard.completedToday": "Terminées Aujourd'hui",
        "dashboard.activeChecklists": "Checklists Actives",
        "dashboard.upcomingMaintenance": "Prochaines Maintenances",
        "dashboard.recentActivity": "Activité Récente",
        "dashboard.quickActions": "Actions Rapides",
        "dashboard.newMaintenance": "Nouvelle Maintenance",
        "dashboard.newChecklist": "Nouvelle Checklist",
        "dashboard.scanQR": "Scanner QR",
        "dashboard.viewAll": "Voir Tout",
        "dashboard.noUpcoming": "Aucune maintenance programmée",
        "dashboard.noActivity": "Aucune activité récente",
        "dashboard.language": "Langue",
        "dashboard.selectLanguage": "Sélectionner la Langue",

        // Equipment
        "equipment.title": "Équipements",
        "equipment.subtitle": "Gérer et surveiller tous les équipements",
        "equipment.new": "Nouvel Équipement",
        "equipment.edit": "Modifier l'Équipement",
        "equipment.details": "Détails de l'Équipement",
        "equipment.name": "Nom de l'Équipement",
        "equipment.code": "Code Équipement",
        "equipment.type": "Type",
        "equipment.category": "Catégorie",
        "equipment.location": "Emplacement",
        "equipment.serialNumber": "Numéro de Série",
        "equipment.manufacturer": "Fabricant",
        "equipment.model": "Modèle",
        "equipment.purchaseDate": "Date d'Achat",
        "equipment.warrantyExpiry": "Fin de Garantie",
        "equipment.status": "Statut",
        "equipment.active": "Actif",
        "equipment.inactive": "Inactif",
        "equipment.maintenance": "En Maintenance",
        "equipment.decommissioned": "Hors Service",
        "equipment.documents": "Documents",
        "equipment.qrCode": "Code QR",
        "equipment.noEquipment": "Aucun équipement trouvé",
        "equipment.noEquipmentDesc": "Commencez par ajouter votre premier équipement",
        "equipment.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cet équipement?",
        "equipment.addEquipment": "Ajouter Équipement",
        "equipment.addFirst": "Ajouter Premier Équipement",
        "equipment.generic": "Générique",
        "equipment.technicalSpecs": "Spécifications Techniques",
        "equipment.technicalSpecsPlaceholder": "Entrez les spécifications techniques...",
        "equipment.notesPlaceholder": "Notes supplémentaires...",
        "equipment.saving": "Enregistrement...",
        "equipment.saveEquipment": "Enregistrer l'Équipement",
        "equipment.showQR": "Afficher Générateur QR",
        "equipment.hideQR": "Masquer Générateur QR",
        "equipment.qrGenerator": "Générateur de Code QR",
        "equipment.information": "Informations Équipement",
        "equipment.required": "obligatoire",
        "equipment.namePlaceholder": "Entrez le nom de l'équipement",
        "equipment.codePlaceholder": "Entrez le code de l'équipement",
        "equipment.typePlaceholder": "ex. Compresseur, Pompe",
        "equipment.categoryPlaceholder": "ex. Machine, Outil",
        "equipment.locationPlaceholder": "ex. Entrepôt A, Étage 2",
        "equipment.serialNumberPlaceholder": "Entrez le numéro de série",
        "equipment.manufacturerPlaceholder": "Entrez le fabricant",
        "equipment.modelPlaceholder": "Entrez le modèle",

        // Maintenance
        "maintenance.title": "Maintenance",
        "maintenance.subtitle": "Gérer et surveiller toutes les maintenances",
        "maintenance.addMaintenance": "Nouvelle Maintenance",
        "maintenance.addFirst": "Ajouter Première Maintenance",
        "maintenance.noMaintenance": "Aucune maintenance trouvée",
        "maintenance.noMaintenanceDesc": "Commencez par ajouter votre première maintenance",
        "maintenance.new": "Nouvelle Maintenance",
        "maintenance.newMaintenance": "Nouvelle Maintenance",
        "maintenance.edit": "Modifier la Maintenance",
        "maintenance.details": "Détails de la Maintenance",
        "maintenance.scheduled": "Programmée",
        "maintenance.inProgress": "En Cours",
        "maintenance.completed": "Terminée",
        "maintenance.cancelled": "Annulée",
        "maintenance.pending": "En Attente",
        "maintenance.type": "Type de Maintenance",
        "maintenance.preventive": "Préventive",
        "maintenance.corrective": "Corrective",
        "maintenance.predictive": "Prédictive",
        "maintenance.scheduledDate": "Date Programmée",
        "maintenance.completedDate": "Date de Fin",
        "maintenance.technician": "Technicien",
        "maintenance.cost": "Coût",
        "maintenance.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette maintenance?",
        "maintenance.selectEquipment": "Sélectionner Équipement",
        "maintenance.selectTechnician": "Sélectionner Technicien",
        "maintenance.frequency": "Fréquence",
        "maintenance.daily": "Quotidienne",
        "maintenance.weekly": "Hebdomadaire",
        "maintenance.monthly": "Mensuelle",
        "maintenance.quarterly": "Trimestrielle",
        "maintenance.yearly": "Annuelle",
        "maintenance.nextDue": "Prochaine Échéance",
        "maintenance.assignTo": "Assigner à",
        "maintenance.titleLabel": "Titre",
        "maintenance.titlePlaceholder": "Entrez le titre de la maintenance",
        "maintenance.descriptionPlaceholder": "Description de la maintenance...",
        "maintenance.createSuccess": "Maintenance créée avec succès",
        "maintenance.createError": "Erreur lors de la création",
        "maintenance.updateSuccess": "Maintenance mise à jour avec succès",
        "maintenance.updateError": "Erreur lors de la mise à jour",

        // Checklists
        "checklists.title": "Checklists",
        "checklists.subtitle": "Gérer et surveiller toutes les checklists",
        "checklists.addChecklist": "Nouvelle Checklist",
        "checklists.addFirst": "Ajouter Première Checklist",
        "checklists.noChecklists": "Aucune checklist trouvée",
        "checklists.noChecklistsDesc": "Commencez par ajouter votre première checklist",
        "checklists.newChecklist": "Nouvelle Checklist",
        "checklists.newChecklistDesc": "Créer un nouveau modèle de checklist avec les éléments à vérifier",
        "checklists.active": "Active",
        "checklists.inactive": "Inactive",
        "checklists.items": "éléments",
        "checklists.execute": "Exécuter",
        "checklists.confirmDelete": "Êtes-vous sûr de vouloir supprimer cette checklist?",
        "checklists.deleteSuccess": "Checklist supprimée avec succès",
        "checklists.deleteError": "Erreur lors de la suppression",
        "checklists.createSuccess": "Checklist créée avec succès",
        "checklists.createError": "Erreur lors de la création",
        "checklists.checklistTitle": "Titre de la Checklist",
        "checklists.titlePlaceholder": "Entrez le titre de la checklist",
        "checklists.titleRequired": "Le titre est obligatoire",
        "checklists.category": "Catégorie",
        "checklists.categoryPlaceholder": "ex. Maintenance Préventive",
        "checklists.categoryRequired": "La catégorie est obligatoire",
        "checklists.equipmentType": "Type d'Équipement",
        "checklists.equipmentTypePlaceholder": "ex. Compresseur, Pompe",
        "checklists.descriptionPlaceholder": "Description de la checklist...",
        "checklists.checklistItems": "Éléments de la Checklist",
        "checklists.addItem": "Ajouter Élément",
        "checklists.itemTitle": "Titre de l'Élément",
        "checklists.itemTitlePlaceholder": "ex. Vérifier le niveau d'huile",
        "checklists.itemDescription": "Description",
        "checklists.itemDescPlaceholder": "Instructions supplémentaires...",
        "checklists.requiredField": "Champ obligatoire",
        "checklists.itemRequired": "Ajoutez au moins un élément",
        "checklists.associatedChecklist": "Checklist Associée",
        "checklists.selectChecklist": "Sélectionner Checklist",
        "checklists.completeAll": "Complétez tous les éléments avant de finaliser",
        "checklists.confirmComplete": "Confirmer la complétion de la checklist",
        "checklists.clearSignature": "Effacer la Signature",
        "checklists.saveSignature": "Sauvegarder la signature pour usage futur",
        "checklists.confirmAndSend": "Confirmer et Envoyer",

        // Users
        "users.title": "Gestion des Utilisateurs",
        "users.new": "Nouvel Utilisateur",
        "users.edit": "Modifier l'Utilisateur",
        "users.email": "Email",
        "users.password": "Mot de passe",
        "users.role": "Rôle",
        "users.admin": "Administrateur",
        "users.technician": "Technicien",
        "users.viewer": "Visualiseur",
        "users.lastLogin": "Dernière Connexion",
        "users.noUsers": "Aucun utilisateur trouvé",
        "users.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cet utilisateur?",

        // Settings
        "settings.title": "Paramètres",
        "settings.profile": "Profil",
        "settings.security": "Sécurité",
        "settings.notifications": "Notifications",
        "settings.appearance": "Apparence",
        "settings.language": "Langue",
        "settings.theme": "Thème",
        "settings.darkMode": "Mode Sombre",
        "settings.lightMode": "Mode Clair",
        "settings.changePassword": "Changer le Mot de passe",
        "settings.twoFactor": "Authentification à Deux Facteurs",
        "settings.emailNotifications": "Notifications Email",
        "settings.pushNotifications": "Notifications Push",

        // Auth
        "auth.login": "Connexion",
        "auth.logout": "Déconnexion",
        "auth.register": "S'inscrire",
        "auth.forgotPassword": "Mot de passe oublié?",
        "auth.resetPassword": "Réinitialiser le Mot de passe",
        "auth.email": "Email",
        "auth.password": "Mot de passe",
        "auth.confirmPassword": "Confirmer le Mot de passe",
        "auth.rememberMe": "Se souvenir de moi",
        "auth.noAccount": "Pas de compte?",
        "auth.hasAccount": "Déjà un compte?",
        "auth.invalidCredentials": "Identifiants invalides",
        "auth.loginSuccess": "Connexion réussie",
        "auth.logoutSuccess": "Déconnexion réussie",

        // Scanner
        "scanner.title": "Scanner QR",
        "scanner.scan": "Scanner",
        "scanner.scanning": "Scan en cours...",
        "scanner.noCamera": "Aucune caméra trouvée",
        "scanner.permissionDenied": "Permission caméra refusée",
        "scanner.equipmentFound": "Équipement trouvé",
        "scanner.equipmentNotFound": "Équipement non trouvé",

        // Notifications
        "notifications.title": "Notifications",
        "notifications.markAllRead": "Tout marquer comme lu",
        "notifications.noNotifications": "Aucune notification",
        "notifications.new": "Nouvelle",

        // Analytics
        "analytics.title": "Analyses",
        "analytics.checklistExecutions": "Exécutions de Checklists",
        "analytics.maintenanceStats": "Statistiques de Maintenance",
        "analytics.equipmentStatus": "État des Équipements",
        "analytics.period": "Période",
        "analytics.today": "Aujourd'hui",
        "analytics.thisWeek": "Cette Semaine",
        "analytics.thisMonth": "Ce Mois",
        "analytics.thisYear": "Cette Année",
    },

    es: {
        // Common
        "common.loading": "Cargando...",
        "common.save": "Guardar",
        "common.cancel": "Cancelar",
        "common.delete": "Eliminar",
        "common.edit": "Editar",
        "common.create": "Crear",
        "common.search": "Buscar",
        "common.filter": "Filtrar",
        "common.export": "Exportar",
        "common.back": "Atrás",
        "common.next": "Siguiente",
        "common.confirm": "Confirmar",
        "common.close": "Cerrar",
        "common.yes": "Sí",
        "common.no": "No",
        "common.all": "Todos",
        "common.none": "Ninguno",
        "common.actions": "Acciones",
        "common.status": "Estado",
        "common.date": "Fecha",
        "common.time": "Hora",
        "common.name": "Nombre",
        "common.description": "Descripción",
        "common.notes": "Notas",
        "common.priority": "Prioridad",
        "common.high": "Alta",
        "common.medium": "Media",
        "common.low": "Baja",
        "common.success": "Éxito",
        "common.error": "Error",
        "common.warning": "Advertencia",

        // Navigation
        "nav.dashboard": "Panel de Control",
        "nav.equipment": "Equipos",
        "nav.maintenance": "Mantenimiento",
        "nav.checklists": "Checklists",
        "nav.analytics": "Análisis",
        "nav.settings": "Configuración",
        "nav.users": "Usuarios",
        "nav.notifications": "Notificaciones",
        "nav.logout": "Cerrar Sesión",
        "nav.scanner": "Escáner QR",

        // Dashboard
        "dashboard.title": "Panel de Control",
        "dashboard.welcome": "Bienvenido",
        "dashboard.totalEquipment": "Equipos Totales",
        "dashboard.pendingMaintenance": "Mantenimientos Pendientes",
        "dashboard.completedToday": "Completados Hoy",
        "dashboard.activeChecklists": "Checklists Activas",
        "dashboard.upcomingMaintenance": "Próximos Mantenimientos",
        "dashboard.recentActivity": "Actividad Reciente",
        "dashboard.quickActions": "Acciones Rápidas",
        "dashboard.newMaintenance": "Nuevo Mantenimiento",
        "dashboard.newChecklist": "Nueva Checklist",
        "dashboard.scanQR": "Escanear QR",
        "dashboard.viewAll": "Ver Todo",
        "dashboard.noUpcoming": "Sin mantenimientos programados",
        "dashboard.noActivity": "Sin actividad reciente",
        "dashboard.language": "Idioma",
        "dashboard.selectLanguage": "Seleccionar Idioma",

        // Equipment
        "equipment.title": "Equipos",
        "equipment.subtitle": "Gestiona y monitorea todos los equipos",
        "equipment.new": "Nuevo Equipo",
        "equipment.edit": "Editar Equipo",
        "equipment.details": "Detalles del Equipo",
        "equipment.name": "Nombre del Equipo",
        "equipment.code": "Código del Equipo",
        "equipment.type": "Tipo",
        "equipment.category": "Categoría",
        "equipment.location": "Ubicación",
        "equipment.serialNumber": "Número de Serie",
        "equipment.manufacturer": "Fabricante",
        "equipment.model": "Modelo",
        "equipment.purchaseDate": "Fecha de Compra",
        "equipment.warrantyExpiry": "Vencimiento de Garantía",
        "equipment.status": "Estado",
        "equipment.active": "Activo",
        "equipment.inactive": "Inactivo",
        "equipment.maintenance": "En Mantenimiento",
        "equipment.decommissioned": "Fuera de Servicio",
        "equipment.documents": "Documentos",
        "equipment.qrCode": "Código QR",
        "equipment.noEquipment": "No se encontraron equipos",
        "equipment.noEquipmentDesc": "Comienza agregando tu primer equipo",
        "equipment.deleteConfirm": "¿Está seguro de que desea eliminar este equipo?",
        "equipment.addEquipment": "Agregar Equipo",
        "equipment.addFirst": "Agregar Primer Equipo",
        "equipment.generic": "Genérico",
        "equipment.technicalSpecs": "Especificaciones Técnicas",
        "equipment.technicalSpecsPlaceholder": "Ingrese las especificaciones técnicas...",
        "equipment.notesPlaceholder": "Notas adicionales...",
        "equipment.saving": "Guardando...",
        "equipment.saveEquipment": "Guardar Equipo",
        "equipment.showQR": "Mostrar Generador QR",
        "equipment.hideQR": "Ocultar Generador QR",
        "equipment.qrGenerator": "Generador de Código QR",
        "equipment.information": "Información del Equipo",
        "equipment.required": "obligatorio",
        "equipment.namePlaceholder": "Ingrese nombre del equipo",
        "equipment.codePlaceholder": "Ingrese código del equipo",
        "equipment.typePlaceholder": "ej. Compresor, Bomba",
        "equipment.categoryPlaceholder": "ej. Maquinaria, Herramienta",
        "equipment.locationPlaceholder": "ej. Almacén A, Piso 2",
        "equipment.serialNumberPlaceholder": "Ingrese número de serie",
        "equipment.manufacturerPlaceholder": "Ingrese fabricante",
        "equipment.modelPlaceholder": "Ingrese modelo",

        // Maintenance
        "maintenance.title": "Mantenimiento",
        "maintenance.subtitle": "Gestiona y monitorea todos los mantenimientos",
        "maintenance.addMaintenance": "Nuevo Mantenimiento",
        "maintenance.addFirst": "Agregar Primer Mantenimiento",
        "maintenance.noMaintenance": "No se encontraron mantenimientos",
        "maintenance.noMaintenanceDesc": "Comienza agregando tu primer mantenimiento",
        "maintenance.new": "Nuevo Mantenimiento",
        "maintenance.newMaintenance": "Nuevo Mantenimiento",
        "maintenance.edit": "Editar Mantenimiento",
        "maintenance.details": "Detalles del Mantenimiento",
        "maintenance.scheduled": "Programado",
        "maintenance.inProgress": "En Progreso",
        "maintenance.completed": "Completado",
        "maintenance.cancelled": "Cancelado",
        "maintenance.pending": "Pendiente",
        "maintenance.type": "Tipo de Mantenimiento",
        "maintenance.preventive": "Preventivo",
        "maintenance.corrective": "Correctivo",
        "maintenance.predictive": "Predictivo",
        "maintenance.scheduledDate": "Fecha Programada",
        "maintenance.completedDate": "Fecha de Finalización",
        "maintenance.technician": "Técnico",
        "maintenance.cost": "Costo",
        "maintenance.deleteConfirm": "¿Está seguro de que desea eliminar este mantenimiento?",
        "maintenance.selectEquipment": "Seleccionar Equipo",
        "maintenance.selectTechnician": "Seleccionar Técnico",
        "maintenance.frequency": "Frecuencia",
        "maintenance.daily": "Diaria",
        "maintenance.weekly": "Semanal",
        "maintenance.monthly": "Mensual",
        "maintenance.quarterly": "Trimestral",
        "maintenance.yearly": "Anual",
        "maintenance.nextDue": "Próxima Fecha",
        "maintenance.assignTo": "Asignar a",
        "maintenance.titleLabel": "Título",
        "maintenance.titlePlaceholder": "Ingrese título del mantenimiento",
        "maintenance.descriptionPlaceholder": "Descripción del mantenimiento...",
        "maintenance.createSuccess": "Mantenimiento creado exitosamente",
        "maintenance.createError": "Error al crear mantenimiento",
        "maintenance.updateSuccess": "Mantenimiento actualizado exitosamente",
        "maintenance.updateError": "Error al actualizar",

        // Checklists
        "checklists.title": "Checklists",
        "checklists.subtitle": "Gestiona y monitorea todas las checklists",
        "checklists.addChecklist": "Nueva Checklist",
        "checklists.addFirst": "Agregar Primera Checklist",
        "checklists.noChecklists": "No se encontraron checklists",
        "checklists.noChecklistsDesc": "Comienza agregando tu primera checklist",
        "checklists.newChecklist": "Nueva Checklist",
        "checklists.newChecklistDesc": "Crea una nueva plantilla de checklist con elementos a verificar",
        "checklists.active": "Activa",
        "checklists.inactive": "Inactiva",
        "checklists.items": "elementos",
        "checklists.execute": "Ejecutar",
        "checklists.confirmDelete": "¿Está seguro de que desea eliminar esta checklist?",
        "checklists.deleteSuccess": "Checklist eliminada exitosamente",
        "checklists.deleteError": "Error al eliminar checklist",
        "checklists.createSuccess": "Checklist creada exitosamente",
        "checklists.createError": "Error al crear checklist",
        "checklists.checklistTitle": "Título de Checklist",
        "checklists.titlePlaceholder": "Ingrese título de checklist",
        "checklists.titleRequired": "El título es obligatorio",
        "checklists.category": "Categoría",
        "checklists.categoryPlaceholder": "ej. Mantenimiento Preventivo",
        "checklists.categoryRequired": "La categoría es obligatoria",
        "checklists.equipmentType": "Tipo de Equipo",
        "checklists.equipmentTypePlaceholder": "ej. Compresor, Bomba",
        "checklists.descriptionPlaceholder": "Descripción de la checklist...",
        "checklists.checklistItems": "Elementos de Checklist",
        "checklists.addItem": "Agregar Elemento",
        "checklists.itemTitle": "Título del Elemento",
        "checklists.itemTitlePlaceholder": "ej. Verificar nivel de aceite",
        "checklists.itemDescription": "Descripción",
        "checklists.itemDescPlaceholder": "Instrucciones adicionales...",
        "checklists.requiredField": "Campo obligatorio",
        "checklists.itemRequired": "Agregue al menos un elemento",
        "checklists.associatedChecklist": "Checklist Asociada",
        "checklists.selectChecklist": "Seleccionar Checklist",
        "checklists.completeAll": "Complete todos los elementos antes de finalizar",
        "checklists.confirmComplete": "Confirmar la finalización de la checklist",
        "checklists.clearSignature": "Borrar Firma",
        "checklists.saveSignature": "Guardar firma para uso futuro",
        "checklists.confirmAndSend": "Confirmar y Enviar",

        // Users
        "users.title": "Gestión de Usuarios",
        "users.new": "Nuevo Usuario",
        "users.edit": "Editar Usuario",
        "users.email": "Correo Electrónico",
        "users.password": "Contraseña",
        "users.role": "Rol",
        "users.admin": "Administrador",
        "users.technician": "Técnico",
        "users.viewer": "Visualizador",
        "users.lastLogin": "Último Acceso",
        "users.noUsers": "No se encontraron usuarios",
        "users.deleteConfirm": "¿Está seguro de que desea eliminar este usuario?",

        // Settings
        "settings.title": "Configuración",
        "settings.profile": "Perfil",
        "settings.security": "Seguridad",
        "settings.notifications": "Notificaciones",
        "settings.appearance": "Apariencia",
        "settings.language": "Idioma",
        "settings.theme": "Tema",
        "settings.darkMode": "Modo Oscuro",
        "settings.lightMode": "Modo Claro",
        "settings.changePassword": "Cambiar Contraseña",
        "settings.twoFactor": "Autenticación de Dos Factores",
        "settings.emailNotifications": "Notificaciones por Email",
        "settings.pushNotifications": "Notificaciones Push",

        // Auth
        "auth.login": "Iniciar Sesión",
        "auth.logout": "Cerrar Sesión",
        "auth.register": "Registrarse",
        "auth.forgotPassword": "¿Olvidó su Contraseña?",
        "auth.resetPassword": "Restablecer Contraseña",
        "auth.email": "Correo Electrónico",
        "auth.password": "Contraseña",
        "auth.confirmPassword": "Confirmar Contraseña",
        "auth.rememberMe": "Recordarme",
        "auth.noAccount": "¿No tiene una cuenta?",
        "auth.hasAccount": "¿Ya tiene una cuenta?",
        "auth.invalidCredentials": "Credenciales inválidas",
        "auth.loginSuccess": "Inicio de sesión exitoso",
        "auth.logoutSuccess": "Cierre de sesión exitoso",

        // Scanner
        "scanner.title": "Escáner QR",
        "scanner.scan": "Escanear",
        "scanner.scanning": "Escaneando...",
        "scanner.noCamera": "No se encontró cámara",
        "scanner.permissionDenied": "Permiso de cámara denegado",
        "scanner.equipmentFound": "Equipo encontrado",
        "scanner.equipmentNotFound": "Equipo no encontrado",

        // Notifications
        "notifications.title": "Notificaciones",
        "notifications.markAllRead": "Marcar todo como leído",
        "notifications.noNotifications": "Sin notificaciones",
        "notifications.new": "Nueva",

        // Analytics
        "analytics.title": "Análisis",
        "analytics.checklistExecutions": "Ejecuciones de Checklists",
        "analytics.maintenanceStats": "Estadísticas de Mantenimiento",
        "analytics.equipmentStatus": "Estado de Equipos",
        "analytics.period": "Período",
        "analytics.today": "Hoy",
        "analytics.thisWeek": "Esta Semana",
        "analytics.thisMonth": "Este Mes",
        "analytics.thisYear": "Este Año",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const languageNames: Record<Language, string> = {
    it: "Italiano",
    en: "English",
    fr: "Français",
    es: "Español",
};

export const languageFlags: Record<Language, string> = {
    it: "🇮🇹",
    en: "🇬🇧",
    fr: "🇫🇷",
    es: "🇪🇸",
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>("it");

    useEffect(() => {
        const savedLanguage = localStorage.getItem("app-language") as Language;
        if (savedLanguage && translations[savedLanguage]) {
            setLanguageState(savedLanguage);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("app-language", lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}

export { languageNames };